# One alarm: too many 5xx responses through the load balancer.
#
# It adds up two ALB metrics, because they catch different failures:
#   HTTPCode_ELB_5XX_Count    - errors generated by the ALB itself, e.g. 503 when no
#                               target is healthy (Phase 5 failures 1, 3, 4 and 5)
#   HTTPCode_Target_5XX_Count - errors returned by the app, e.g. an unhandled 500

# Not KMS-encrypted on purpose: CloudWatch alarms cannot publish to a topic encrypted
# with the AWS-managed aws/sns key, and a customer-managed key would cost $1/month.
resource "aws_sns_topic" "alarms" {
  name = "${local.name}-alarms"
}

# Only created when an email is set. AWS sends a confirmation link that must be clicked.
resource "aws_sns_topic_subscription" "alarm_email" {
  count = var.alarm_email == "" ? 0 : 1

  topic_arn = aws_sns_topic.alarms.arn
  protocol  = "email"
  endpoint  = var.alarm_email
}

resource "aws_cloudwatch_metric_alarm" "alb_5xx" {
  alarm_name        = "${local.name}-alb-5xx"
  alarm_description = "5 or more 5xx responses (ALB + app) within 5 minutes"

  comparison_operator = "GreaterThanOrEqualToThreshold"
  threshold           = 5
  evaluation_periods  = 1

  # No traffic means no data points, and no traffic is not an outage.
  treat_missing_data = "notBreaching"

  metric_query {
    id          = "total_5xx"
    expression  = "FILL(elb_5xx, 0) + FILL(target_5xx, 0)"
    label       = "ALB + target 5xx"
    return_data = true
  }

  metric_query {
    id = "elb_5xx"
    metric {
      namespace   = "AWS/ApplicationELB"
      metric_name = "HTTPCode_ELB_5XX_Count"
      dimensions  = { LoadBalancer = aws_lb.main.arn_suffix }
      stat        = "Sum"
      period      = 300
    }
  }

  metric_query {
    id = "target_5xx"
    metric {
      namespace   = "AWS/ApplicationELB"
      metric_name = "HTTPCode_Target_5XX_Count"
      dimensions  = { LoadBalancer = aws_lb.main.arn_suffix }
      stat        = "Sum"
      period      = 300
    }
  }

  alarm_actions = [aws_sns_topic.alarms.arn]
  ok_actions    = [aws_sns_topic.alarms.arn] # also notify when it recovers
}
