package io.github.pallavinile98.claims.service;

import io.github.pallavinile98.claims.domain.Claim;
import io.github.pallavinile98.claims.domain.ClaimStatus;
import io.github.pallavinile98.claims.domain.CurrentUser;
import io.github.pallavinile98.claims.domain.Role;
import io.github.pallavinile98.claims.dto.ClaimResponse;
import io.github.pallavinile98.claims.dto.CreateClaimRequest;
import io.github.pallavinile98.claims.exception.ClaimNotFoundException;
import io.github.pallavinile98.claims.exception.ForbiddenActionException;
import io.github.pallavinile98.claims.exception.InvalidStateTransitionException;
import io.github.pallavinile98.claims.repository.ClaimRepository;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.test.util.ReflectionTestUtils;

import java.math.BigDecimal;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.AdditionalAnswers.returnsFirstArg;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Service rules with the repository mocked out: no Spring context, no database.
 * The ClaimStatus table is tested on its own; these tests prove the service
 * actually goes through it, for every action from every starting status.
 */
@ExtendWith(MockitoExtension.class)
class ClaimServiceTest {

    private static final long CLAIM_ID = 1L;
    private static final CurrentUser ALICE = new CurrentUser("alice", Role.SUBMITTER);
    private static final CurrentUser MALLORY = new CurrentUser("mallory", Role.SUBMITTER);
    private static final CurrentUser BOB = new CurrentUser("bob", Role.APPROVER);
    // Same id as the submitter, but acting as an approver: the self-approval case.
    private static final CurrentUser ALICE_AS_APPROVER = new CurrentUser("alice", Role.APPROVER);

    @Mock
    private ClaimRepository repository;

    @InjectMocks
    private ClaimService service;

    /** Stubs the repository to return one of alice's claims, already in the given status. */
    private Claim aliceClaimIn(ClaimStatus status) {
        Claim claim = new Claim("Taxi", "Airport", new BigDecimal("42.50"), "alice");
        ReflectionTestUtils.setField(claim, "id", CLAIM_ID); // normally generated by Postgres
        claim.changeStatus(status);
        when(repository.findById(CLAIM_ID)).thenReturn(Optional.of(claim));
        lenient().when(repository.saveAndFlush(any())).thenAnswer(returnsFirstArg());
        return claim;
    }

    @Nested
    class Transitions {

        @ParameterizedTest(name = "submit from {0}: succeeds = {1}")
        @CsvSource({"DRAFT, true", "SUBMITTED, false", "APPROVED, false", "REJECTED, false"})
        void submit(ClaimStatus start, boolean succeeds) {
            Claim claim = aliceClaimIn(start);
            if (succeeds) {
                assertThat(service.submit(ALICE, CLAIM_ID).status()).isEqualTo(ClaimStatus.SUBMITTED);
            } else {
                assertRejectedWithoutChange(() -> service.submit(ALICE, CLAIM_ID), claim, start);
            }
        }

        @ParameterizedTest(name = "approve from {0}: succeeds = {1}")
        @CsvSource({"DRAFT, false", "SUBMITTED, true", "APPROVED, false", "REJECTED, false"})
        void approve(ClaimStatus start, boolean succeeds) {
            Claim claim = aliceClaimIn(start);
            if (succeeds) {
                ClaimResponse result = service.approve(BOB, CLAIM_ID);
                assertThat(result.status()).isEqualTo(ClaimStatus.APPROVED);
                assertThat(result.approverId()).isEqualTo("bob");
            } else {
                assertRejectedWithoutChange(() -> service.approve(BOB, CLAIM_ID), claim, start);
            }
        }

        @ParameterizedTest(name = "reject from {0}: succeeds = {1}")
        @CsvSource({"DRAFT, false", "SUBMITTED, true", "APPROVED, false", "REJECTED, false"})
        void reject(ClaimStatus start, boolean succeeds) {
            Claim claim = aliceClaimIn(start);
            if (succeeds) {
                ClaimResponse result = service.reject(BOB, CLAIM_ID);
                assertThat(result.status()).isEqualTo(ClaimStatus.REJECTED);
                assertThat(result.approverId()).isEqualTo("bob");
            } else {
                assertRejectedWithoutChange(() -> service.reject(BOB, CLAIM_ID), claim, start);
            }
        }

        /** An illegal move must throw 409 AND leave the claim untouched and unsaved. */
        private void assertRejectedWithoutChange(Runnable action, Claim claim, ClaimStatus start) {
            assertThatThrownBy(action::run).isInstanceOf(InvalidStateTransitionException.class);
            assertThat(claim.getStatus()).isEqualTo(start);
            assertThat(claim.getApproverId()).isNull();
            verify(repository, never()).saveAndFlush(any());
        }
    }

    @Nested
    class Permissions {

        @Test
        void submitterCreatesDraftOwnedByThem() {
            when(repository.save(any())).thenAnswer(returnsFirstArg());

            ClaimResponse created = service.create(ALICE,
                    new CreateClaimRequest("Taxi", null, new BigDecimal("42.50")));

            assertThat(created.status()).isEqualTo(ClaimStatus.DRAFT);
            assertThat(created.submitterId()).isEqualTo("alice");
        }

        @Test
        void approverCannotCreate() {
            assertThatThrownBy(() -> service.create(BOB,
                    new CreateClaimRequest("Taxi", null, BigDecimal.TEN)))
                    .isInstanceOf(ForbiddenActionException.class);
            verify(repository, never()).save(any());
        }

        @Test
        void approverCannotSubmit() {
            assertThatThrownBy(() -> service.submit(BOB, CLAIM_ID))
                    .isInstanceOf(ForbiddenActionException.class);
        }

        @Test
        void submitterCannotSubmitSomeoneElsesClaim() {
            aliceClaimIn(ClaimStatus.DRAFT);
            assertThatThrownBy(() -> service.submit(MALLORY, CLAIM_ID))
                    .isInstanceOf(ForbiddenActionException.class);
        }

        @Test
        void submitterCannotApprove() {
            assertThatThrownBy(() -> service.approve(ALICE, CLAIM_ID))
                    .isInstanceOf(ForbiddenActionException.class);
        }

        @Test
        void submitterCannotReject() {
            assertThatThrownBy(() -> service.reject(ALICE, CLAIM_ID))
                    .isInstanceOf(ForbiddenActionException.class);
        }

        @Test
        void approverCannotApproveOwnClaim() {
            Claim claim = aliceClaimIn(ClaimStatus.SUBMITTED);
            assertThatThrownBy(() -> service.approve(ALICE_AS_APPROVER, CLAIM_ID))
                    .isInstanceOf(ForbiddenActionException.class);
            assertThat(claim.getStatus()).isEqualTo(ClaimStatus.SUBMITTED);
        }

        @Test
        void approverCannotRejectOwnClaim() {
            Claim claim = aliceClaimIn(ClaimStatus.SUBMITTED);
            assertThatThrownBy(() -> service.reject(ALICE_AS_APPROVER, CLAIM_ID))
                    .isInstanceOf(ForbiddenActionException.class);
            assertThat(claim.getStatus()).isEqualTo(ClaimStatus.SUBMITTED);
        }

        @Test
        void submitterCannotViewSomeoneElsesClaim() {
            aliceClaimIn(ClaimStatus.DRAFT);
            assertThatThrownBy(() -> service.get(MALLORY, CLAIM_ID))
                    .isInstanceOf(ForbiddenActionException.class);
        }

        @Test
        void approverCanViewAnyClaim() {
            aliceClaimIn(ClaimStatus.SUBMITTED);
            assertThat(service.get(BOB, CLAIM_ID).submitterId()).isEqualTo("alice");
        }

        @Test
        void missingClaimIsNotFound() {
            when(repository.findById(99L)).thenReturn(Optional.empty());
            assertThatThrownBy(() -> service.get(BOB, 99L))
                    .isInstanceOf(ClaimNotFoundException.class);
        }
    }

    @Nested
    class Listing {

        @Test
        void approverWithoutFilterSeesAllClaims() {
            when(repository.findAll(any(Pageable.class))).thenReturn(Page.empty());
            service.list(BOB, null, 0, 20);
            verify(repository).findAll(any(Pageable.class));
        }

        @Test
        void submitterOnlySeesOwnClaims() {
            when(repository.findBySubmitterIdAndStatus(eq("alice"), eq(ClaimStatus.DRAFT), any()))
                    .thenReturn(Page.empty());
            service.list(ALICE, ClaimStatus.DRAFT, 0, 20);
            verify(repository).findBySubmitterIdAndStatus(eq("alice"), eq(ClaimStatus.DRAFT), any());
            verify(repository, never()).findByStatus(any(), any());
            verify(repository, never()).findAll(any(Pageable.class));
        }
    }
}
